// lib/uiText.ts
// ─────────────────────────────────────────────────────────────────────
// Teks antarmuka untuk bagian yang ditambahkan setelah berkas terjemahan
// utama disusun: menu navigasi, tombol bantuan, penjelasan mode, dan
// pesan-pesan pendek lainnya.
//
// Dipisah dari translations.ts agar penambahan teks baru tidak menuntut
// perubahan tipe yang menyentuh delapan blok bahasa sekaligus.
// Bahasa yang belum tersedia jatuh ke Inggris.
// ─────────────────────────────────────────────────────────────────────

type Kamus = Record<string, string>;

const TEKS: Record<string, Kamus> = {
  en: {
    resumeTitle: 'Resume previous session?',
    resumeStartNew: 'Start fresh',
    resumeContinue: 'Resume',
    resumeOrdersLeft: 'orders left',
    resumeRunningPnl: 'running P&L',
    resumeNote: 'Resuming keeps that P&L (Stop Loss/Profit limits are still counted from the start of the session).',
    resumeFailed: 'Failed to resume the session',
    affiliateWebBlocked: 'This account can only be used in the Android app. Please open Stockity AutoTrade on your phone.',
    registerAppOnly: 'New accounts can only be created in the Android app. Download the app first, then register from there.',
    registerAppOnlyTitle: 'Registration is app-only',
    registerAppOnlyDesc: 'New accounts are created directly in the Android app so your account is secure from the start.',
    downloadApp: 'Download Android App',
    haveAccount: 'Already have an account? Sign in',
    navDashboard: 'Dashboard',
    navHistory: 'History',
    navGuide: 'Guide',
    navProfile: 'Profile',
    sessionRunning: 'A session is still running — please stay on this page. Stop it before switching menus.',
    helpButton: 'Need help?',
    helpOnline: 'Support available 24 hours',
    fetchSignals: 'Get Signals — next 6 hours',
    modeSchedule: 'You enter the times and directions yourself, and the bot executes exactly at those times. Best if you already have a signal list.',
    modeFastrade: 'The bot compares prices across two consecutive minutes, then follows the winning direction. Runs continuously without you entering signals.',
    modeCtc: 'Same as Fastrade, but the direction is reversed. Used when the market often turns after moving.',
    modeAiSignal: 'The bot decides the direction itself and executes right away. You only set the amount and stop limits.',
    modeIndicator: 'The bot reads indicators such as RSI or moving averages, and enters when the conditions are met. You choose which indicator.',
    modeMomentum: 'The bot watches for specific candle patterns and only enters when one appears. Fewer orders, but more selective.',
  },
  id: {
    resumeTitle: 'Lanjutkan sesi sebelumnya?',
    resumeStartNew: 'Mulai baru',
    resumeContinue: 'Lanjutkan',
    resumeOrdersLeft: 'order tersisa',
    resumeRunningPnl: 'P&L berjalan',
    resumeNote: 'Melanjutkan akan mempertahankan P&L tersebut (batas Stop Loss/Profit tetap dihitung dari awal sesi).',
    resumeFailed: 'Gagal melanjutkan sesi',
    affiliateWebBlocked: 'Akun ini hanya dapat digunakan lewat aplikasi Android. Silakan buka aplikasi Stockity AutoTrade di ponsel Anda.',
    registerAppOnly: 'Pendaftaran akun baru hanya dapat dilakukan lewat aplikasi Android. Unduh aplikasinya lebih dulu, lalu daftar dari sana.',
    registerAppOnlyTitle: 'Pendaftaran hanya lewat aplikasi',
    registerAppOnlyDesc: 'Akun baru dibuat langsung dari aplikasi Android agar akun Anda aman sejak awal.',
    downloadApp: 'Unduh Aplikasi Android',
    haveAccount: 'Sudah punya akun? Masuk',
    navDashboard: 'Dashboard',
    navHistory: 'Riwayat',
    navGuide: 'Panduan',
    navProfile: 'Profil',
    sessionRunning: 'Mode masih aktif — jangan tinggalkan halaman ini. Hentikan sesinya dulu sebelum berpindah menu.',
    helpButton: 'Ada permasalahan?',
    helpOnline: 'Layanan bantuan online 24 jam',
    fetchSignals: 'Ambil Sinyal — 6 jam ke depan',
    modeSchedule: 'Anda menuliskan sendiri jam dan arahnya, lalu bot mengeksekusi tepat pada jam tersebut. Cocok bila Anda sudah punya daftar sinyal.',
    modeFastrade: 'Bot membandingkan harga dua menit berturut-turut, lalu ikut arah yang sedang menang. Berjalan terus tanpa perlu Anda masukkan sinyal.',
    modeCtc: 'Mirip Fastrade, tetapi arahnya dibalik dari hasil perbandingan. Dipakai saat pasar sering berbalik arah setelah bergerak.',
    modeAiSignal: 'Bot menentukan arah sendiri lalu langsung mengeksekusi. Anda cukup mengatur nominal dan batas berhenti.',
    modeIndicator: 'Bot membaca indikator seperti RSI atau moving average, lalu masuk saat syaratnya terpenuhi. Anda bisa memilih indikatornya.',
    modeMomentum: 'Bot mengamati pola candle tertentu, dan hanya masuk ketika pola itu muncul. Ordernya lebih jarang tetapi lebih terpilih.',
  },
  ru: {
    resumeTitle: 'Продолжить прошлую сессию?',
    resumeStartNew: 'Начать заново',
    resumeContinue: 'Продолжить',
    resumeOrdersLeft: 'ордеров осталось',
    resumeRunningPnl: 'текущий P&L',
    resumeNote: 'Продолжение сохранит этот результат (лимиты Stop Loss/Profit считаются с начала сессии).',
    resumeFailed: 'Не удалось продолжить сессию',
    affiliateWebBlocked: 'Этот аккаунт можно использовать только в приложении для Android. Откройте Stockity AutoTrade на телефоне.',
    registerAppOnly: 'Новые аккаунты создаются только в приложении для Android. Сначала скачайте приложение.',
    registerAppOnlyTitle: 'Регистрация только в приложении',
    registerAppOnlyDesc: 'Аккаунт создаётся прямо в приложении, чтобы он был защищён с самого начала.',
    downloadApp: 'Скачать приложение для Android',
    haveAccount: 'Уже есть аккаунт? Войти',
    navDashboard: 'Панель',
    navHistory: 'История',
    navGuide: 'Руководство',
    navProfile: 'Профиль',
    sessionRunning: 'Сессия ещё идёт — не покидайте эту страницу. Сначала остановите её.',
    helpButton: 'Нужна помощь?',
    helpOnline: 'Поддержка работает круглосуточно',
    fetchSignals: 'Получить сигналы — на 6 часов',
    modeSchedule: 'Вы сами вводите время и направление, а бот исполняет точно в указанное время. Подходит, если список сигналов уже есть.',
    modeFastrade: 'Бот сравнивает цены двух соседних минут и следует за победившим направлением. Работает без ввода сигналов.',
    modeCtc: 'Как Fastrade, но направление обратное. Используется, когда рынок часто разворачивается после движения.',
    modeAiSignal: 'Бот сам определяет направление и сразу исполняет. Вы задаёте только сумму и лимиты остановки.',
    modeIndicator: 'Бот читает индикаторы, например RSI или скользящие средние, и входит при выполнении условий.',
    modeMomentum: 'Бот ждёт появления определённых свечных моделей. Сделок меньше, но они более отобранные.',
  },
  es: {
    resumeTitle: '¿Reanudar la sesión anterior?',
    resumeStartNew: 'Empezar de nuevo',
    resumeContinue: 'Reanudar',
    resumeOrdersLeft: 'órdenes restantes',
    resumeRunningPnl: 'P&L en curso',
    resumeNote: 'Reanudar conserva ese P&L (los límites de Stop Loss/Profit se cuentan desde el inicio de la sesión).',
    resumeFailed: 'No se pudo reanudar la sesión',
    affiliateWebBlocked: 'Esta cuenta solo puede usarse en la aplicación de Android. Abre Stockity AutoTrade en tu teléfono.',
    registerAppOnly: 'Las cuentas nuevas solo se crean en la aplicación de Android. Descarga la app y regístrate desde allí.',
    registerAppOnlyTitle: 'El registro solo está en la app',
    registerAppOnlyDesc: 'Las cuentas nuevas se crean en la app de Android para que tu cuenta esté protegida desde el principio.',
    downloadApp: 'Descargar app de Android',
    haveAccount: '¿Ya tienes cuenta? Inicia sesión',
    navDashboard: 'Panel',
    navHistory: 'Historial',
    navGuide: 'Guía',
    navProfile: 'Perfil',
    sessionRunning: 'Hay una sesión en curso: no salgas de esta página. Deténla antes de cambiar de menú.',
    helpButton: '¿Necesitas ayuda?',
    helpOnline: 'Soporte disponible 24 horas',
    fetchSignals: 'Obtener señales — próximas 6 horas',
    modeSchedule: 'Tú escribes las horas y direcciones, y el bot ejecuta justo a esa hora. Ideal si ya tienes una lista de señales.',
    modeFastrade: 'El bot compara precios de dos minutos seguidos y sigue la dirección ganadora. Funciona sin que introduzcas señales.',
    modeCtc: 'Igual que Fastrade, pero con la dirección invertida. Útil cuando el mercado suele girar tras moverse.',
    modeAiSignal: 'El bot decide la dirección por sí mismo y ejecuta de inmediato. Solo configuras el importe y los límites.',
    modeIndicator: 'El bot lee indicadores como RSI o medias móviles y entra cuando se cumplen las condiciones.',
    modeMomentum: 'El bot espera patrones de velas concretos y solo entra cuando aparecen. Menos órdenes, más selectivas.',
  },
  ms: {
    resumeTitle: 'Sambung sesi sebelumnya?',
    resumeStartNew: 'Mula baharu',
    resumeContinue: 'Sambung',
    resumeOrdersLeft: 'order berbaki',
    resumeRunningPnl: 'P&L berjalan',
    resumeNote: 'Menyambung akan mengekalkan P&L itu (had Stop Loss/Profit tetap dikira dari awal sesi).',
    resumeFailed: 'Gagal menyambung sesi',
    affiliateWebBlocked: 'Akaun ini hanya boleh digunakan melalui aplikasi Android. Sila buka Stockity AutoTrade di telefon anda.',
    registerAppOnly: 'Akaun baharu hanya boleh didaftarkan melalui aplikasi Android. Muat turun aplikasinya dahulu.',
    registerAppOnlyTitle: 'Pendaftaran hanya melalui aplikasi',
    registerAppOnlyDesc: 'Akaun baharu dibuat terus dari aplikasi Android supaya akaun anda selamat sejak awal.',
    downloadApp: 'Muat Turun Aplikasi Android',
    haveAccount: 'Sudah ada akaun? Log masuk',
    navDashboard: 'Papan Pemuka',
    navHistory: 'Sejarah',
    navGuide: 'Panduan',
    navProfile: 'Profil',
    sessionRunning: 'Sesi masih berjalan — jangan tinggalkan halaman ini. Hentikan dahulu sebelum bertukar menu.',
    helpButton: 'Ada masalah?',
    helpOnline: 'Sokongan tersedia 24 jam',
    fetchSignals: 'Ambil Isyarat — 6 jam akan datang',
    modeSchedule: 'Anda menulis sendiri masa dan arahnya, dan bot melaksanakan tepat pada masa itu. Sesuai jika anda sudah ada senarai isyarat.',
    modeFastrade: 'Bot membandingkan harga dua minit berturut-turut, lalu mengikut arah yang menang. Berjalan tanpa anda memasukkan isyarat.',
    modeCtc: 'Sama seperti Fastrade, tetapi arahnya diterbalikkan. Digunakan apabila pasaran kerap berpatah balik.',
    modeAiSignal: 'Bot menentukan arah sendiri lalu terus melaksanakan. Anda hanya menetapkan jumlah dan had berhenti.',
    modeIndicator: 'Bot membaca penunjuk seperti RSI atau purata bergerak, dan masuk apabila syaratnya dipenuhi.',
    modeMomentum: 'Bot menunggu corak lilin tertentu dan hanya masuk apabila ia muncul. Order lebih jarang tetapi lebih terpilih.',
  },
  hi: {
    resumeTitle: 'पिछला सत्र जारी रखें?',
    resumeStartNew: 'नया शुरू करें',
    resumeContinue: 'जारी रखें',
    resumeOrdersLeft: 'ऑर्डर शेष',
    resumeRunningPnl: 'चालू P&L',
    resumeNote: 'जारी रखने पर वह P&L बना रहेगा (Stop Loss/Profit सीमाएँ सत्र की शुरुआत से गिनी जाती हैं)।',
    resumeFailed: 'सत्र जारी नहीं किया जा सका',
    affiliateWebBlocked: 'यह खाता केवल Android ऐप में उपयोग किया जा सकता है। कृपया अपने फ़ोन पर ऐप खोलें।',
    registerAppOnly: 'नए खाते केवल Android ऐप में बनाए जा सकते हैं। पहले ऐप डाउनलोड करें।',
    registerAppOnlyTitle: 'पंजीकरण केवल ऐप में',
    registerAppOnlyDesc: 'नए खाते सीधे Android ऐप में बनाए जाते हैं ताकि आपका खाता शुरू से सुरक्षित रहे।',
    downloadApp: 'Android ऐप डाउनलोड करें',
    haveAccount: 'पहले से खाता है? साइन इन करें',
    navDashboard: 'डैशबोर्ड',
    navHistory: 'इतिहास',
    navGuide: 'गाइड',
    navProfile: 'प्रोफ़ाइल',
    sessionRunning: 'सत्र अभी चल रहा है — कृपया इस पृष्ठ पर बने रहें। मेनू बदलने से पहले इसे रोकें।',
    helpButton: 'मदद चाहिए?',
    helpOnline: 'सहायता 24 घंटे उपलब्ध',
    fetchSignals: 'सिग्नल लें — अगले 6 घंटे',
    modeSchedule: 'आप स्वयं समय और दिशा दर्ज करते हैं, और बॉट ठीक उसी समय ऑर्डर करता है।',
    modeFastrade: 'बॉट लगातार दो मिनट की कीमतों की तुलना करता है और जीतने वाली दिशा का अनुसरण करता है।',
    modeCtc: 'Fastrade जैसा ही, पर दिशा उलटी होती है। तब उपयोगी जब बाज़ार अक्सर पलटता है।',
    modeAiSignal: 'बॉट स्वयं दिशा तय करता है और तुरंत ऑर्डर करता है। आप केवल राशि और सीमाएँ तय करते हैं।',
    modeIndicator: 'बॉट RSI या मूविंग एवरेज जैसे संकेतक पढ़ता है और शर्तें पूरी होने पर प्रवेश करता है।',
    modeMomentum: 'बॉट कुछ विशेष कैंडल पैटर्न की प्रतीक्षा करता है। ऑर्डर कम होते हैं पर अधिक चुने हुए।',
  },
  th: {
    resumeTitle: 'ดำเนินเซสชันก่อนหน้าต่อ?',
    resumeStartNew: 'เริ่มใหม่',
    resumeContinue: 'ดำเนินต่อ',
    resumeOrdersLeft: 'ออร์เดอร์คงเหลือ',
    resumeRunningPnl: 'P&L ปัจจุบัน',
    resumeNote: 'การดำเนินต่อจะคง P&L ไว้ (ขีดจำกัด Stop Loss/Profit นับจากต้นเซสชัน)',
    resumeFailed: 'ไม่สามารถดำเนินเซสชันต่อได้',
    affiliateWebBlocked: 'บัญชีนี้ใช้ได้เฉพาะในแอป Android กรุณาเปิดแอปบนโทรศัพท์ของคุณ',
    registerAppOnly: 'สร้างบัญชีใหม่ได้เฉพาะในแอป Android กรุณาดาวน์โหลดแอปก่อน',
    registerAppOnlyTitle: 'สมัครได้เฉพาะในแอป',
    registerAppOnlyDesc: 'บัญชีใหม่ถูกสร้างในแอป Android โดยตรงเพื่อความปลอดภัยตั้งแต่แรก',
    downloadApp: 'ดาวน์โหลดแอป Android',
    haveAccount: 'มีบัญชีอยู่แล้ว? เข้าสู่ระบบ',
    navDashboard: 'แดชบอร์ด',
    navHistory: 'ประวัติ',
    navGuide: 'คู่มือ',
    navProfile: 'โปรไฟล์',
    sessionRunning: 'เซสชันยังทำงานอยู่ — โปรดอยู่ในหน้านี้ หยุดก่อนเปลี่ยนเมนู',
    helpButton: 'ต้องการความช่วยเหลือ?',
    helpOnline: 'ฝ่ายสนับสนุนพร้อมบริการ 24 ชั่วโมง',
    fetchSignals: 'รับสัญญาณ — 6 ชั่วโมงข้างหน้า',
    modeSchedule: 'คุณกรอกเวลาและทิศทางเอง แล้วบอทจะเข้าออร์เดอร์ตามเวลานั้น',
    modeFastrade: 'บอทเปรียบเทียบราคาสองนาทีติดกัน แล้วตามทิศทางที่ชนะ',
    modeCtc: 'เหมือน Fastrade แต่กลับทิศทาง ใช้เมื่อตลาดมักกลับตัวหลังเคลื่อนไหว',
    modeAiSignal: 'บอทกำหนดทิศทางเองแล้วเข้าออร์เดอร์ทันที คุณตั้งเพียงจำนวนเงินและขีดจำกัด',
    modeIndicator: 'บอทอ่านอินดิเคเตอร์ เช่น RSI หรือเส้นค่าเฉลี่ย และเข้าเมื่อเงื่อนไขครบ',
    modeMomentum: 'บอทรอรูปแบบแท่งเทียนบางอย่าง ออร์เดอร์น้อยกว่าแต่คัดเลือกมากกว่า',
  },
  tr: {
    resumeTitle: 'Önceki oturuma devam edilsin mi?',
    resumeStartNew: 'Yeniden başla',
    resumeContinue: 'Devam et',
    resumeOrdersLeft: 'emir kaldı',
    resumeRunningPnl: 'güncel P&L',
    resumeNote: 'Devam etmek bu P&L değerini korur (Stop Loss/Profit sınırları oturum başından sayılır).',
    resumeFailed: 'Oturuma devam edilemedi',
    affiliateWebBlocked: 'Bu hesap yalnızca Android uygulamasında kullanılabilir. Lütfen telefonunuzda uygulamayı açın.',
    registerAppOnly: 'Yeni hesaplar yalnızca Android uygulamasında oluşturulur. Önce uygulamayı indirin.',
    registerAppOnlyTitle: 'Kayıt yalnızca uygulamada',
    registerAppOnlyDesc: 'Yeni hesaplar doğrudan Android uygulamasında oluşturulur, böylece hesabınız en baştan güvende olur.',
    downloadApp: 'Android Uygulamasını İndir',
    haveAccount: 'Hesabınız var mı? Giriş yapın',
    navDashboard: 'Panel',
    navHistory: 'Geçmiş',
    navGuide: 'Rehber',
    navProfile: 'Profil',
    sessionRunning: 'Oturum hâlâ çalışıyor — lütfen bu sayfada kalın. Menü değiştirmeden önce durdurun.',
    helpButton: 'Yardım gerekiyor mu?',
    helpOnline: 'Destek 24 saat açık',
    fetchSignals: 'Sinyal Al — sonraki 6 saat',
    modeSchedule: 'Saatleri ve yönleri kendiniz girersiniz, bot tam o saatte işlem açar.',
    modeFastrade: 'Bot ardışık iki dakikanın fiyatlarını karşılaştırır ve kazanan yönü izler.',
    modeCtc: 'Fastrade ile aynı, ancak yön terstir. Piyasa hareketten sonra sık dönüyorsa kullanılır.',
    modeAiSignal: 'Bot yönü kendi belirler ve hemen işlem açar. Siz yalnızca tutarı ve limitleri ayarlarsınız.',
    modeIndicator: 'Bot RSI veya hareketli ortalama gibi göstergeleri okur ve koşullar sağlanınca girer.',
    modeMomentum: 'Bot belirli mum formasyonlarını bekler. Daha az ama daha seçici işlem açar.',
  },
};

/** Ambil teks sesuai bahasa; bahasa yang belum tersedia jatuh ke Inggris. */
export function ui(lang: string | undefined, kunci: string): string {
  const kamus = (lang && TEKS[lang]) || TEKS.en;
  return kamus[kunci] ?? TEKS.en[kunci] ?? kunci;
}
